services:
  rss-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rss-api
    ports:
      - "3000:3000"
    environment:
      - ADD_KEY=${ADD_KEY}
      - VERCEL_BLOB_STORE_NAME=${VERCEL_BLOB_STORE_NAME}
      - CACHE_MINUTES=${CACHE_MINUTES}
    volumes:
      - ./sdd:/app/api/sdd  # 修改挂载路径，因为现在在 server 目录下
    restart: unless-stopped 